# Generated by Django 6.0.5 on 2026-05-24 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED', 'Picked Up'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('REASSIGNED', 'Reassigned')], default='ASSIGNED', max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('earning_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_earning_credited', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_boy', models.ForeignKey(limit_choices_to={'role': 'DELIVERY_BOY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order')),
            ],
            options={
                'db_table': 'delivery_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('WALKING', 'Walking')], default='BICYCLE', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('success_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DELIVERY_BOY'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_boy_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.deliveryassignment')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_ratings',
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_logs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['delivery_boy', '-recorded_at'], name='location_lo_deliver_0c6c6e_idx')],
            },
        ),
    ]
