# Generated by Django 6.0.5 on 2026-05-24 15:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='locationlog',
            name='location_lo_deliver_0c6c6e_idx',
        ),
        migrations.RenameField(
            model_name='deliveryassignment',
            old_name='is_earning_credited',
            new_name='assigned_by_admin',
        ),
        migrations.RenameField(
            model_name='deliveryassignment',
            old_name='earning_amount',
            new_name='earning',
        ),
        migrations.RenameField(
            model_name='deliveryboyprofile',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='deliveryboyprofile',
            old_name='is_approved',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='deliveryboyprofile',
            old_name='location_updated_at',
            new_name='last_location_update',
        ),
        migrations.RenameField(
            model_name='deliveryboyprofile',
            old_name='total_earnings',
            new_name='total_earned',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='deliveryassignment',
            name='pickup_lon',
        ),
        migrations.RemoveField(
            model_name='deliveryboyprofile',
            name='success_rate',
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='successful_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locationlog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='delivery.deliveryassignment'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_boy',
            field=models.ForeignKey(limit_choices_to={'role': 'DELIVERY_BOY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='deliveryboyprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('SCOOTER', 'Scooter'), ('ON_FOOT', 'On Foot')], default='MOTORCYCLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryrating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
