# Generated by Django 6.0.5 on 2026-05-24 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.ForeignKey(limit_choices_to={'role': 'DELIVERY_BOY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday_collections', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_collections', to='shops.shop')),
            ],
            options={
                'db_table': 'sunday_collections',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='UdhaarRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OVERDUE', 'Overdue'), ('SETTLED', 'Settled'), ('PARTIAL', 'Partially Settled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='udhaar_taken', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='udhaar_record', to='orders.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='udhaar_given', to='shops.shop')),
            ],
            options={
                'db_table': 'udhaar_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UdhaarPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('WALLET', 'Wallet'), ('UPI', 'UPI')], default='CASH', max_length=10)),
                ('utr_number', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='udhaar_collections', to=settings.AUTH_USER_MODEL)),
                ('udhaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='udhaar.udhaarrecord')),
            ],
            options={
                'db_table': 'udhaar_payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
