# Generated by Django 6.0.5 on 2026-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='used_count',
            new_name='uses_count',
        ),
        migrations.RenameField(
            model_name='couponusage',
            old_name='discount_given',
            new_name='discount_applied',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max discount for percentage type', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
