# Generated by Django 6.0.5 on 2026-05-25 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('color_hex', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_zones',
            },
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('landmark_type', models.CharField(choices=[('SCHOOL', 'School'), ('HOSPITAL', 'Hospital'), ('MASJID', 'Masjid'), ('MANDIR', 'Mandir'), ('BAZAAR', 'Bazaar'), ('BUS_STOP', 'Bus Stop'), ('PANCHAYAT', 'Panchayat Office'), ('BANK', 'Bank / ATM'), ('SHOP', 'Shop'), ('OTHER', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('village', models.CharField(default='Reoti', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landmarks',
                'ordering': ['landmark_type', 'name'],
            },
        ),
    ]
