# Generated by Django 6.0.5 on 2026-05-24 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='created_by',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_dde14f_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='body',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('WEATHER_ALERT', 'Weather Alert'), ('UDHAAR_REMINDER', 'Udhaar Reminder'), ('EMI_REMINDER', 'EMI Reminder'), ('CHAT', 'Chat Message'), ('BROADCAST', 'Admin Broadcast'), ('SYSTEM', 'System')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reference_type',
        ),
    ]
